NuGet/NuGet.Server

src/NuGet.Server/Core/FrameworkNameExtensions.cs
src/NuGet.Server/Core/ServiceResolver.cs
src/NuGet.Server/Infrastructure/IPackagesSerializer.cs
src/NuGet.Server/Infrastructure/IServerPackageStore.cs
src/NuGet.Server/Infrastructure/JsonNetPackagesSerializer.cs
src/NuGet.Server/Infrastructure/SemanticVersionJsonConverter.cs
src/NuGet.Server/Infrastructure/ServerPackage.cs
src/NuGet.Server/Infrastructure/ServerPackageRepository.cs
src/NuGet.Server/Infrastructure/ServerPackageStore.cs
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/Web.config
src/NuGet.Server/packages.config
test/NuGet.Server.Tests/JsonNetPackagesSerializerTests.cs
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj
test/NuGet.Server.Tests/SemanticVersionJsonConverterTests.cs
test/NuGet.Server.Tests/ServerPackageRepositoryTest.cs
test/NuGet.Server.Tests/packages.config

See https://github.com/NuGet/NuGetGallery/issues/2843

NuGet.Server - Cache package metadata to disk

---

src/NuGet.Server/Strings.resx

Make sure to check the following when opening a pull request:
* If it's a large contribution, please open a regular issue first and discuss with the team
* Make sure the PR targets the `dev` branch
Having that said: thank you for your contribution already!
String has "fiels" instead of "files".

Corrected typo in symbols ignore string

---

src/NuGet.Server/Infrastructure/ServerPackageRepository.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/3277.
The symptoms described in the bug can occur if the following sequence of events occurs:
1. `allowOverrideExistingPackageOnPush` is set to `true`.
1. A file watcher event is triggered which results in the cache being cleared (e.g. some file is deleted)
1. A package is pushed.
This will result in a package cache with a single package in it: the one that was just pushed. When the list of packages is queried, only the one package (and any packages pushed after it) will be visible.
/cc @emgarten @maartenba @shishirx34

Keep track of whether the cache needs rebuilding

---

Enable-Signing.ps1
Sign-Packages.ps1

The necessary changes to run this build on VSTS instead of TeamCity, which includes moving some scripts from TeamCity to this repository.

Integrate NuGet.Server build with VSTS

---

src/NuGet.Server/DataServices/Packages.svc.cs
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/NuGet.Server.nuspec
src/NuGet.Server/packages.config
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj
test/NuGet.Server.Tests/packages.config

This addresses https://github.com/NuGet/NuGetGallery/issues/3578.
You'll never guess who fixed this:
https://github.com/OData/odata.net/commit/f10d515b4498cfe703b96b7fd0d35aca2347d5e3
/cc @maartenba
Version 5.7.0 is the first one with this fix:
https://github.com/OData/odata.net/releases/tag/5.7.0

Use Microsoft.Data.Services instead of System.Data.Services

---

src/NuGet.Server/Web.config

I feel almost stupid for submitting such a baby PR... :)

Fix a single tiny typo

---

src/NuGet.Server.Core/Infrastructure/IServerPackageCache.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageCache.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageStore.cs
src/NuGet.Server.V2/Controllers/NuGetODataController.cs
test/NuGet.Server.Core.Tests/Infrastructure/TemporaryDirectory.cs
test/NuGet.Server.Core.Tests/ServerPackageCacheTest.cs
test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs

Fix https://github.com/NuGet/NuGetGallery/issues/3434

Re-evaluate IsLatest properties when a package is delisted

---

src/NuGet.Server.Core/DataServices/PackageExtensions.cs
test/NuGet.Server.Core.Tests/PackageExtensionsTest.cs

Fix https://github.com/NuGet/NuGetGallery/issues/4020

When a package is unlisted, return the package's published date as 1900

---

src/NuGet.Server.Core/DataServices/PackageExtensions.cs
src/NuGet.Server.Core/Infrastructure/IServerPackageCache.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageCache.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageStore.cs
src/NuGet.Server.V2/Controllers/NuGetODataController.cs
test/NuGet.Server.Core.Tests/Infrastructure/TemporaryDirectory.cs
test/NuGet.Server.Core.Tests/PackageExtensionsTest.cs
test/NuGet.Server.Core.Tests/ServerPackageCacheTest.cs
test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs

Merge dev into master for the 3.0.1 release

---

src/NuGet.Server.V2/Controllers/NuGetODataController.cs
test/NuGet.Server.Tests/IntegrationTests.cs

This will be NuGet.Server 3.0.2, fixing https://github.com/NuGet/NuGetGallery/issues/5193.

Merge dev into master

---

src/NuGet.Server/App_Start/NuGetODataConfig.cs
src/NuGet.Server/App_Start/NuGetODataConfig.cs.pp
src/NuGet.Server/Infrastructure/TraceExceptionLogger.cs
src/NuGet.Server/NuGet.Server.csproj

Also, commented out example of how to log traces to a file.

In the template C# file NuGetODataConfig.cs.pp, log exceptions to Trace

---

src/NuGet.Server.Core/Infrastructure/IServerPackageRepository.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageRepositoryExtensions.cs
src/NuGet.Server.V2/Controllers/NuGetODataController.cs
test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs

Use includeDelisted query parameter

---

src/NuGet.Server.Core/NuGet.Server.Core.nuspec
src/NuGet.Server.V2/NuGet.Server.V2.nuspec
src/NuGet.Server/NuGet.Server.nuspec

Add repository type and URL to .nuspec

---

build.ps1
samples/NuGet.Server.V2.Samples.OwinHost/NuGet.Server.V2.Samples.OwinHost.csproj
samples/NuGet.Server.V2.Samples.OwinHost/packages.config
src/NuGet.Server.Core/NuGet.Server.Core.csproj
src/NuGet.Server.Core/packages.config
src/NuGet.Server.V2/NuGet.Server.V2.csproj
src/NuGet.Server.V2/packages.config
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/packages.config
test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj
test/NuGet.Server.V2.Tests/NuGet.Server.V2.Tests.csproj

https://github.com/NuGet/Engineering/issues/1728

Configure MicroBuild to sign NuGet.Server

---

build.ps1
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/packages.config
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj

Port of https://github.com/NuGet/NuGet.Server/pull/65 to 2.x

Configure MicroBuild to sign NuGet.Server 2.x

---

.nuget/packages.config
build.ps1
build/sign.proj

Address https://github.com/NuGet/Engineering/issues/1816

Enable package signing on NuGet.Server .nupkgs

---

samples/NuGet.Server.V2.Samples.OwinHost/NuGet.Server.V2.Samples.OwinHost.csproj
samples/NuGet.Server.V2.Samples.OwinHost/app.config
samples/NuGet.Server.V2.Samples.OwinHost/packages.config
src/NuGet.Server.V2/NuGet.Server.V2.csproj
src/NuGet.Server.V2/NuGet.Server.V2.nuspec
src/NuGet.Server.V2/app.config
src/NuGet.Server.V2/packages.config
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/Web.config
src/NuGet.Server/packages.config
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj
test/NuGet.Server.Tests/app.config
test/NuGet.Server.Tests/packages.config
test/NuGet.Server.V2.Tests/NuGet.Server.V2.Tests.csproj
test/NuGet.Server.V2.Tests/app.config
test/NuGet.Server.V2.Tests/packages.config

Address https://github.com/NuGet/Engineering/issues/2524

Update Microsoft.Data.OData to 5.8.4

---

src/NuGet.Server.Core/Core/DuplicatePackageException.cs
src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs
src/NuGet.Server.Core/NuGet.Server.Core.csproj
src/NuGet.Server.V2/Controllers/NuGetODataController.cs
test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs
test/NuGet.Server.Tests/IntegrationTests.cs

Related to: [Push Command option to Skip Existing Packages](https://github.com/NuGet/NuGet.Client/pull/2802)

Added support for new -SkipDuplicate option in NuGet 5.1

---

.gitignore
build.ps1

Progress on https://github.com/NuGet/Engineering/issues/1821

Batch sign the binaries

---

.editorconfig
NuGet.Server.sln
samples/NuGet.Server.V2.Samples.OwinHost/NuGet.Server.V2.Samples.OwinHost.csproj
samples/NuGet.Server.V2.Samples.OwinHost/packages.config
src/NuGet.Server.Core/NuGet.Server.Core.csproj
src/NuGet.Server.Core/packages.config
src/NuGet.Server.V2/NuGet.Server.V2.csproj
src/NuGet.Server.V2/packages.config
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/packages.config
test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj
test/NuGet.Server.Core.Tests/packages.config
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj
test/NuGet.Server.Tests/packages.config
test/NuGet.Server.V2.Tests/NuGet.Server.V2.Tests.csproj
test/NuGet.Server.V2.Tests/packages.config

* Add static code analysis 
1. Add package reference 
2. Add global editor config
Address: https://github.com/NuGet/Engineering/issues/3417

Add code analysis

---

.editorconfig
.gitignore
NuGet.Server.sln
build.ps1
samples/NuGet.Server.V2.Samples.OwinHost/NuGet.Server.V2.Samples.OwinHost.csproj
samples/NuGet.Server.V2.Samples.OwinHost/packages.config
src/NuGet.Server.Core/NuGet.Server.Core.csproj
src/NuGet.Server.Core/packages.config
src/NuGet.Server.V2/NuGet.Server.V2.csproj
src/NuGet.Server.V2/packages.config
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/packages.config
test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj
test/NuGet.Server.Core.Tests/packages.config
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj
test/NuGet.Server.Tests/packages.config
test/NuGet.Server.V2.Tests/NuGet.Server.V2.Tests.csproj
test/NuGet.Server.V2.Tests/packages.config

[ReleasePrep][2021.06.28]RI of dev into main

---

samples/NuGet.Server.V2.Samples.OwinHost/NuGet.Server.V2.Samples.OwinHost.csproj
samples/NuGet.Server.V2.Samples.OwinHost/app.config
samples/NuGet.Server.V2.Samples.OwinHost/packages.config
src/NuGet.Server.Core/NuGet.Server.Core.csproj
src/NuGet.Server.Core/NuGet.Server.Core.nuspec
src/NuGet.Server.Core/packages.config
src/NuGet.Server.V2/NuGet.Server.V2.csproj
src/NuGet.Server.V2/NuGet.Server.V2.nuspec
src/NuGet.Server.V2/app.config
src/NuGet.Server.V2/packages.config
src/NuGet.Server/NuGet.Server.csproj
src/NuGet.Server/Web.config
src/NuGet.Server/packages.config
test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj
test/NuGet.Server.Core.Tests/packages.config
test/NuGet.Server.Tests/NuGet.Server.Tests.csproj
test/NuGet.Server.Tests/app.config
test/NuGet.Server.Tests/packages.config
test/NuGet.Server.V2.Tests/NuGet.Server.V2.Tests.csproj
test/NuGet.Server.V2.Tests/app.config
test/NuGet.Server.V2.Tests/packages.config

Updated the Newtonsoft.Json package from 9.0.1 to 13.0.1.
Part of https://github.com/NuGet/Engineering/issues/4452

Update Newtonsoft.Json to 13.0.1

---

src/NuGet.Server.V2/Controllers/NuGetODataController.cs

Suppress false positive CodeQL warnings

CodeQL suppression

---

SECURITY.md
src/NuGet.Server.V2/Controllers/NuGetODataController.cs

Suppress false positive CodeQL warnings

Dev to main

---

src/NuGet.Server/Default.aspx

Suppresses false-positive CodeQL report on the Default.aspx page

Suppress false-positive CodeQL
