NuGet/NuGet.Server

src/NuGet.Server/Web.config
See https://github.com/NuGet/NuGetGallery/issues/2951
> Ran into an issue which turned out to be relatively simple to fix, but seemed unnecessary work.
> Running NuGet.Server in a NAT'ed network with a public IP which was different from the server's internal IP caused the atom feed to return its internal IP for all incoming requests and made it impossible to actually download the packages as user's couldn't access the server via the internal IP.
> After digging into it, I realized that simply adding an appSetting for "aspnet:UseHostHeaderForRequestUrl" set to "true" resolved the issue easily enough.
> It seems like it would be better to default this to true by default, or at the very least, add it to the web.config commented out with a description explaining it just to help others find …
=> Default to using the host header for request urls

NuGet.config, src/NuGet.Server.Core/NuGet.Server.Core.csproj, src/NuGet.Server.Core/packages.config, src/NuGet.Server/NuGet.Server.csproj, src/NuGet.Server/packages.config, test/NuGet.Server.Core.Tests/NormalizeVersionInterceptorTest.cs, test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj, test/NuGet.Server.Core.Tests/SemanticVersionJsonConverterTests.cs, test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs, test/NuGet.Server.Core.Tests/packages.config, test/NuGet.Server.Tests/NuGet.Server.Tests.csproj, test/NuGet.Server.Tests/packages.config
Update NuGet.Core reference to 2.14 for server 2.0
Expand semver tests to include semver 2.0 type versions.
@emgarten @shishirx34 @maartenba @xavierdecoster
=> Add SemVer2.0 Support

src/NuGet.Server/Web.config
Fixes https://github.com/NuGet/NuGetGallery/issues/3217 - NuGet.Server web.config has inconsistent default values for max upload size. 
From http://stackoverflow.com/questions/6327452/which-gets-priority-maxrequestlength-or-maxallowedcontentlength it seems that we should ideally set the `maxRequestLength` to be a smaller value than that of the `maxAllowedContentLength`, so that appropriate error handler can be invoked, application error vs IIS error.
Both values are now set to ~30Mb. Let me know if that is not the desired value for Nuget.Server.
/cc @xavierdecoster @maartenba @skofman1 @ryuyu @scottbommarito
=> Fix maxRequestLength value

.gitignore, build.cmd, src/CommonAssemblyInfo.cs, src/NuGet.Server/NuGet.Server.csproj, src/NuGet.Server/NuGet.Server.nuspec, src/NuGet.Server/packages.config, test/NuGet.Server.Tests/NuGet.Server.Tests.csproj, test/NuGet.Server.Tests/packages.config
.nupkg directory structure change:
```
content\Default.aspx                -->   content\net46\Default.aspx
content\favicon.ico                 -->   content\net46\favicon.ico
content\Packages                    -->   content\net46\Packages
content\Web.config                  -->   content\net46\Web.config
content\web.config.install.xdt      -->   content\net46\web.config.install.xdt
content\DataServices\Packages.svc   -->   content\net46\DataServices\Packages.svc
content\DataServices\Routes.cs.pp   -->   content\net46\DataServices\Routes.cs.pp
content\Packages\Readme.txt         -->   content\net46\Packages\Readme.txt
lib\net46\NuGet.Server.dll          -->   lib\net46\NuGet.Server.dll
```
Needed to pack a .nuspec for NuGet.Server instead of a .csproj so we can set the content files to …
=> Pack NuGet.Server from .nuspec instead of .csproj to control content subdirectory (net46)

.gitignore, NuGet.Server.sln, NuGet.config, build.cmd, samples/NuGet.Server.V2.Samples.OwinHost/NuGet.Server.V2.Samples.OwinHost.csproj, samples/NuGet.Server.V2.Samples.OwinHost/app.config, samples/NuGet.Server.V2.Samples.OwinHost/packages.config, src/CommonAssemblyInfo.cs, src/NuGet.Server.Core/NuGet.Server.Core.csproj, src/NuGet.Server.Core/NuGet.Server.Core.nuspec, src/NuGet.Server.Core/packages.config, src/NuGet.Server.V2/NuGet.Server.V2.csproj, src/NuGet.Server.V2/NuGet.Server.V2.nuspec, src/NuGet.Server.V2/app.config, src/NuGet.Server.V2/packages.config, src/NuGet.Server/App_Start/NuGetODataConfig.cs, src/NuGet.Server/App_Start/NuGetODataConfig.cs.pp, src/NuGet.Server/NuGet.Server.csproj, src/NuGet.Server/NuGet.Server.nuspec, src/NuGet.Server/Web.config, src/NuGet.Server/packages.config, test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj, test/NuGet.Server.Core.Tests/packages.config, test/NuGet.Server.Tests/NuGet.Server.Tests.csproj, test/NuGet.Server.Tests/app.config, test/NuGet.Server.Tests/packages.config, test/NuGet.Server.V2.Tests/NuGet.Server.V2.Tests.csproj, test/NuGet.Server.V2.Tests/app.config, test/NuGet.Server.V2.Tests/packages.config
1. Pack NuGet.Server from .nuspec instead of .csproj to control content subdirectory
1. Make NuGet.Server.Core and NuGet.Server.V2 have net46-only dependencies
1. Use the .pp file to initialize NuGet.Server routes, instead of web activator in NuGet.Server.dll. This is like NuGet.Server 2.11.2.
1. Bump dependency versions.
This PR is analogous to https://github.com/NuGet/NuGet.Server/pull/21 but is against `dev` instead of `master`.
Open questions:
1. Should we bump the major version of NuGet.Server to signal to users that we've moved to WebAPI?
/cc @emgarten @xavierdecoster @maartenba @andulv
=> Make packages only net46 compatible (which matches the DLLs)

.gitignore, src/NuGet.Server/DataServices/PackageExtensions.cs, src/NuGet.Server/Infrastructure/ServerPackage.cs, src/NuGet.Server/Infrastructure/ServerPackageRepository.cs, src/NuGet.Server/Infrastructure/ServerPackageStore.cs, test/NuGet.Server.Tests/NuGet.Server.Tests.csproj, test/NuGet.Server.Tests/ServerPackageStoreTest.cs, test/NuGet.Server.Tests/packages.config
While investigating https://github.com/NuGet/NuGetGallery/issues/3277, I found these issue. This PR does not address the underlying issue in https://github.com/NuGet/NuGetGallery/issues/3277, as far as I know.
1. Use the `ServerPackage.Created` for `ODataPackage.Published` (which is based off of file creation time). We are already using `ServerPackage.LastUpdated` (based off of file modification time).
1. Make `Id` and `Version` required for JSON deserialization from the cache file.
1. Catch `JsonSerializationException` when reading the cache file. This can occur when a JSON array has no closing character (`]`). This case indicates a corrupted cache file.
1. Add .sha512 and .nuspec files under the drop directory to the .gitignore.
/cc @emgarten @maartenba
=> Minor bug fixes in NuGet.Server

src/NuGet.Server.Core/Infrastructure/IServerPackageRepository.cs, src/NuGet.Server.Core/Infrastructure/IServerPackageStore.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageExtensions.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageRepositoryExtensions.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageStore.cs, src/NuGet.Server.V2/Controllers/NuGetODataController.cs, src/NuGet.Server/Controllers/PackagesODataController.cs, test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs, test/NuGet.Server.Core.Tests/ServerPackageStoreTest.cs, test/NuGet.Server.V2.Tests/Infrastructure/ControllerTestHelpers.cs, test/NuGet.Server.V2.Tests/NuGetODataControllerTests.cs
To facilitate async IO operations at the bottom of the stack, I have changed `IServerPackageRepository`, `IServerPackageStore`, and `NuGetODataController` to be async.
This will ease future improvements such as switching from NuGet.Core (sync APIs) to NuGet 3.x/4.x (a lot of async APIs).
/cc @dtivel @emgarten @maartenba
=> Make the controller and repository stack async

src/NuGet.Server.Core/Infrastructure/IServerPackageCache.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageCache.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs, test/NuGet.Server.Core.Tests/ServerPackageCacheTest.cs, test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs
This was a bug introduced by my move to `async` (PR https://github.com/NuGet/NuGet.Server/pull/28).
- Fix deadlock when reading packages from the drop folder.
- Fix potential race condition when two of the same packages are added at the same time.
- Make `allowOverrideExistingPackageOnPush` default to false in repository. It is already defaults to false in the configuration.
- Added tests to validate these changes.
/cc @dtivel
=> Fix deadlock when reading packages from the drop folder

src/NuGet.Server.Core/NuGet.Server.Core.csproj, src/NuGet.Server.V2/NuGet.Server.V2.csproj, src/NuGet.Server/Default.aspx
Addresses https://github.com/NuGet/NuGetGallery/issues/3656.
1. Include auto-generated assembly info file
1. Use a NuGet.Server.dll type for front page version
1. Don't show the example push command if the API key has not been configured
=> Include auto-generated assembly metadata

src/NuGet.Server.Core/Infrastructure/JsonNetPackagesSerializer.cs, src/NuGet.Server.Core/Infrastructure/ServerPackage.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageCache.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs, test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj, test/NuGet.Server.Core.Tests/ServerPackageCacheTest.cs, test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs, test/NuGet.Server.Core.Tests/ServerPackageTest.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/3657.
This is adhering to the latest (internal) SemVer 2.0.0 protocol specification.
=> SemVer 2.0.0 version ranges imply that the package itself is SemVer 2.0.0

src/NuGet.Server/DataServices/ODataPackage.cs
In commit 9a2dd68 an EntityPropertyMapping attribute was added to the ODataPackage class which removed the published date from the OData output, causing Visual Studio to not display a published date for packages.  This changes the EntityPropertyMapping attribute to include the published date in the OData output again so Visual Studio can display a published date for packages.
This would resolve issue NuGet/NuGetGallery#4689.
=> Change ODataPackage so its Published property is included in output

src/NuGet.Server.V2/Controllers/NuGetODataController.cs, test/NuGet.Server.Tests/IntegrationTests.cs
Fix https://github.com/NuGet/NuGetGallery/issues/5193
/cc @cmreddyv 
The `EnableQuery` attribute is not needed since the system query parameters (e.g. `$filter`, `$select`) are validated by our `QueryResult` type:
https://github.com/NuGet/NuGet.Server/blob/2972fb387fe65ba03635d5ab76a223e6c38b1a29/src/NuGet.Server.V2/Model/QueryResult.cs#L252-L269
=> Support projection on the Packages() endpoint ($select)

src/NuGet.Server.Core/Core/NullFileSystem.cs, src/NuGet.Server.Core/Core/PackageFactory.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs, src/NuGet.Server.Core/NuGet.Server.Core.csproj, src/NuGet.Server.V2/Controllers/NuGetODataController.cs, test/NuGet.Server.Core.Tests/Core/PackageFactoryTest.cs, test/NuGet.Server.Core.Tests/NuGet.Server.Core.Tests.csproj, test/NuGet.Server.Tests/IntegrationTests.cs
Address https://github.com/NuGet/NuGetGallery/issues/5230 by introducing a null file system abstraction that no-ops when `OptimizedZipArchive` tries to extract the package content.
I decided to keep using the `OptimizedZipPackage` because it does have a cache of the file listing which lives as long as the process does.
https://github.com/NuGet/NuGet2/blob/57bcfab043703778f242080fedc7237d36a6af98/src/Core/Packages/OptimizedZipPackage.cs#L27-L28
Rohit, you were the last to make changes to `OptimizedZipPackage` so I added you.
=> Don't extract the entire package to the %TMP% directory

samples/NuGet.Server.V2.Samples.OwinHost/DictionarySettingsProvider.cs, samples/NuGet.Server.V2.Samples.OwinHost/Program.cs, src/NuGet.Server.Core/Infrastructure/DefaultSettingsProvider.cs, src/NuGet.Server.Core/Infrastructure/ISettingsProvider.cs, src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs, src/NuGet.Server.Core/Strings.Designer.cs, src/NuGet.Server.Core/Strings.resx, src/NuGet.Server/Infrastructure/WebConfigSettingsProvider.cs, src/NuGet.Server/Web.config, test/NuGet.Server.Core.Tests/Infrastructure/FuncSettingsProvider.cs, test/NuGet.Server.Core.Tests/ServerPackageRepositoryTest.cs
Background for pull request: I have two nuget server sites sharing the same package repository folder. One public with authentication, and one internal. In this scenario I get file lock errors on the cache file, so I need to be able to configure different cache files for each site.
=> Configurable cache file name

src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs
I am using NuGet.Server in multi node (10 nodes) deployment model, all the nodes pointing to the same packages file share. For each node pointing at the same share, a cache file is created with the name of the machine.
In the file system changed event, when a file is changed in a subdirectory, the cache is invalidated (10 caches in my case). The problem is that in my scenario, when the cache file itself is updated, the nuget server fails to recognize the updated cache is located in the root folder, so it should not trigger invalidation of the other caches monitoring the same folder.
The consequence is that I always have 1 valid cache and 9 empty caches. This causes severe performance issues because the cache is always rebuilt and we have thousands of packages.
The application allows …
=> Normalize directories before comparing paths in file changed event in order to avoid erroneous cache invalidation in a multi-node deploymeny 

src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs, src/NuGet.Server/App_Start/NuGetODataConfig.cs, src/NuGet.Server/App_Start/NuGetODataConfig.cs.pp, src/NuGet.Server/Infrastructure/TraceExceptionLogger.cs, src/NuGet.Server/NuGet.Server.csproj
This will be made into NuGet.Server 3.1.1. It introduced two fixes:
1. Normalized directories before comparing paths in file changed event (https://github.com/NuGet/NuGet.Server/pull/54)
1. Add `TraceExceptionLogger` so unhandled exceptions are logged to `Trace (https://github.com/NuGet/NuGet.Server/pull/53)
=> Merge dev into master

src/NuGet.Server.V2/NuGetV2WebApiEnabler.cs
Between NuGet.Server v2.8.50926.602 and NuGet.Server v3.1.2.0 the route to push a package was changed from `/api/v2/packages` to `/nuget`. 
When using nuget.exe, if using the root url it will append `api/v2/packages`.
For example, 
```
.\Nuget.exe push "{thing}.nupkg" -s http://localhost:40221 -Verbosity detailed
Pushing {package} 1.2.3 to 'http://localhost:40221'...
PUT http://localhost:40221/api/v2/package/
```
This change will allow users to continue to push packages to `api/v2/packages` so they don't have to edit their existing deployment scripts when doing a Nuget.Server upgrade.
=> Add route to match older Nuget.Server uploads

src/NuGet.Server.V2/NuGetV2WebApiEnabler.cs, src/NuGet.Server/App_Start/NuGetODataConfig.cs, src/NuGet.Server/App_Start/NuGetODataConfig.cs.pp, test/NuGet.Server.Tests/IntegrationTests.cs, test/NuGet.Server.Tests/TestablePackagesODataController.cs
This only affects the NuGetV2WebApiEnabler.UseNuGetV2WebApiFeed API. NuGet.Server still enables the legacy push route by default since it already assumes there is only one feed in the application.
Address https://github.com/NuGet/NuGetGallery/issues/7008
/cc @Levente0xFFFF
=> Don't enable the legacy push route by default

src/NuGet.Server.Core/Infrastructure/JsonNetPackagesSerializer.cs, test/NuGet.Server.Core.Tests/JsonNetPackagesSerializerTests.cs
Address https://github.com/NuGet/NuGetGallery/issues/7414.
See https://github.com/JamesNK/Newtonsoft.Json/issues/2128 for more context.
NuGet.Core always parses things as absolute URIs so it's not possible for strings only parsable as relative to it into the system.
The weird case is something like `//fileserver/Framework/NuGet/server.png` which is parsable as both relative and absolute.
=> Force package metadata URLs to be parsed as absolute URIs

build.ps1
- BuildBranch was changed to BuildBranchCommit to reflect the actual value.
- BuildBranchCommit now points to the newest commit that's needed for migrating to new Agent Pools.
=> [Microbuild] NuGet.Server Update ServerCommon commit on build.ps1.

.gitignore
`artifacts` directory contains the build output and needs to be ignored by git.
=> Adding artifacts directory to .gitignore
